Repository laboratorio-de-praticas/votacao-fe, pull requests merged in 2025-04, with the labels that each got.

#59 Refactor: Aprimoramento do layout da página de confirmação (interna)
  src/app/votacao/interna/confirmacao/page.js
Labels: enhancement

#75 🩹 `Ajuste do botão`
  src/app/votacao/interna/confirmacao/page.js
  src/app/votacao/publica/confirmacao/avaliador/page.js
  src/app/votacao/publica/confirmacao/convidado/page.js
  src/components/congratsText.js
  src/components/projectCard.js
Labels: bug, enhancement

#78 ✨ feat: Adicionar controle de estado ao botão de confirmação + 🐛 fix: Ajustar variáveis no compose.yml
  compose.yml
  src/app/votacao/interna/confirmacao/page.js
  src/components/button.js
  src/components/congratsText.js
Labels: enhancement

#84 Refactor: Remover o componente `CongratsText` da página de confirmação
  src/app/votacao/interna/confirmacao/page.js
Labels: bug

#92 🐛 fix: Corrigir fluxo de estados do botão de votação
  src/app/votacao/interna/confirmacao/page.js
Labels: bug
